name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install black
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade black
      - name: Run black
        run: python -m black ./
